library(dplyr)
library(ggplot2)
library(shiny)
library(shinythemes)
library(readr)
library(shinydashboard)
library(plotly)

referrers <- read_csv("data/syn_referrers.csv")
social_network <- read_csv("data/syn_social_network.csv")
landing_page <- read_csv("data/syn_landing_page.csv")
goals <- read_csv("data/syn_goals.csv")
sessions <- read_csv("data/syn_sessions.csv")
landing_goals <- read_csv("data/syn_landing_goals.csv")
